=== rubenmenino/EDC/proj1EDC/app/static/xml/anuncios.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="anuncios" type="anunciosType"/>
  <xs:complexType name="imagensType">
    <xs:sequence>
      <xs:element type="xs:string" name="imagem"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="anuncioType">
    <xs:sequence>
      <xs:element type="xs:integer" name="id"/>
      <xs:element name="venda">
      <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="vendido"/>
            <xs:enumeration value="naovendido"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:integer" name="preco"/>
      <xs:element type="xs:string" name="nome"/>
      <xs:element type="xs:string" name="contacto"/>
      <xs:element type="xs:string" name="email"/>
      <xs:element type="xs:string" name="marca"/>
      <xs:element type="xs:string" name="modelo"/>
      <xs:element type="xs:integer" name="cilindrada"/>
      <xs:element name="combustivel">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="gasoleo"/>
            <xs:enumeration value="gasolina"/>
            <xs:enumeration value="híbrido(gasolina)"/>
            <xs:enumeration value="híbrido(gasoleo)"/>
            <xs:enumeration value="elétrico"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="transmissao">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="manual"/>
            <xs:enumeration value="automático"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="registo">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:pattern value="[0-9][0-9][0-9][0-9]"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="mes">
      <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="janeiro"/>
            <xs:enumeration value="fevereiro"/>
            <xs:enumeration value="março"/>
            <xs:enumeration value="abril"/>
            <xs:enumeration value="maio"/>
            <xs:enumeration value="junho"/>
            <xs:enumeration value="julho"/>
            <xs:enumeration value="agosto"/>
            <xs:enumeration value="setembro"/>
            <xs:enumeration value="outubro"/>
            <xs:enumeration value="novembro"/>
            <xs:enumeration value="dezembro"/>
            <xs:enumeration value="Janeiro"/>
            <xs:enumeration value="Fevereiro"/>
            <xs:enumeration value="Março"/>
            <xs:enumeration value="Abril"/>
            <xs:enumeration value="Maio"/>
            <xs:enumeration value="Junho"/>
            <xs:enumeration value="Julho"/>
            <xs:enumeration value="Agosto"/>
            <xs:enumeration value="Setembro"/>
            <xs:enumeration value="Outubro"/>
            <xs:enumeration value="Novembro"/>
            <xs:enumeration value="Dezembro"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="estado">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="usado"/>
            <xs:enumeration value="novo"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:integer" name="potencia"/>
      <xs:element type="xs:integer" name="quilometros"/>
      <xs:element type="xs:integer" name="numportas"/>
      <xs:element type="xs:integer" name="lotacao"/>
      <xs:element type="imagensType" name="imagens"/>
      <xs:element type="xs:string" name="descricao"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="anunciosType">
    <xs:sequence>
      <xs:element type="anuncioType" name="anuncio" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== rubenmenino/EDC/proj1EDC/app/static/xml/anuncios.xml
<?xml version="1.0" encoding="utf-8"?>
<anuncios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="anuncios.xsd">
	<anuncio>
		<id>1</id>
        <venda>naovendido</venda>
		<preco>22000</preco>
		<nome>João</nome>
		<contacto>234234234</contacto>
		<email>limao@limonada.pt</email>
		<marca>renault</marca>
		<modelo>megane</modelo>
		<cilindrada>2000</cilindrada>
		<combustivel>gasoleo</combustivel>
		<transmissao>manual</transmissao>
		<registo>2017</registo>
		<mes>maio</mes>
		<estado>usado</estado>
		<potencia>220</potencia>
		<quilometros>7000</quilometros>
		<numportas>5</numportas>
		<lotacao>5</lotacao>
		<imagens><imagem>1.png</imagem></imagens>
		<descricao>Carro cinco estrelas, muito bem mantido, venha ver e apreciar.</descricao>
	</anuncio>
	<anuncio>
		<id>2</id>
        <venda>naovendido</venda>
		<preco>23000</preco>
		<nome>José</nome>
		<contacto>234234235</contacto>
		<email>ananas@limonada.pt</email>
		<marca>renault</marca>
		<modelo>megane</modelo>
		<cilindrada>2000</cilindrada>
		<combustivel>gasoleo</combustivel>
		<transmissao>manual</transmissao>
		<registo>2019</registo>
		<mes>abril</mes>
		<estado>novo</estado>
		<potencia>220</potencia>
		<quilometros>50</quilometros>
		<numportas>5</numportas>
		<lotacao>5</lotacao>
		<imagens><imagem>2.png</imagem></imagens>
		<descricao>Carro novo, versão Bose com todos os extras.</descricao>
	</anuncio>
	<anuncio>
		<id>3</id>
        <venda>naovendido</venda>
		<preco>20000</preco>
		<nome>João</nome>
		<contacto>234234236</contacto>
		<email>maracuja@limonada.pt</email>
		<marca>renault</marca>
		<modelo>clio</modelo>
		<cilindrada>1500</cilindrada>
		<combustivel>gasoleo</combustivel>
		<transmissao>automático</transmissao>
		<registo>2020</registo>
		<mes>junho</mes>
		<estado>usado</estado>
		<potencia>90</potencia>
		<quilometros>18000</quilometros>
		<numportas>5</numportas>
		<lotacao>5</lotacao>
		<imagens><imagem>3.png</imagem></imagens>
		<descricao>Clio a gasoleo com caixa automática, tem câmara de marcha atrás e ar condicionado automático</descricao>
	</anuncio>
	<anuncio>
		<id>4</id>
        <venda>naovendido</venda>
		<preco>55000</preco>
		<nome>Catarina</nome>
		<contacto>234234222</contacto>
		<email>pistachio@limonada.pt</email>
		<marca>mercedes</marca>
		<modelo>a35</modelo>
		<cilindrada>1998</cilindrada>
		<combustivel>gasolina</combustivel>
		<transmissao>automático</transmissao>
		<registo>2019</registo>
		<mes>dezembro</mes>
		<estado>usado</estado>
		<potencia>300</potencia>
		<quilometros>6500</quilometros>
		<numportas>5</numportas>
		<lotacao>5</lotacao>
		<imagens><imagem>4.png</imagem></imagens>
		<descricao>Mercedes classe A, amg 35, com michelin pilot sport 4s, câmara 360, distronic plus, baquets com memória.</descricao>
	</anuncio>
	<anuncio>
		<id>5</id>
        <venda>naovendido</venda>
		<preco>45000</preco>
		<nome>Josefina</nome>
		<contacto>234234664</contacto>
		<email>tomate@limonada.pt</email>
		<marca>mercedes</marca>
		<modelo>e300e</modelo>
		<cilindrada>2000</cilindrada>
		<combustivel>híbrido(gasolina)</combustivel>
		<transmissao>automático</transmissao>
		<registo>2019</registo>
		<mes>março</mes>
		<estado>usado</estado>
		<potencia>300</potencia>
		<quilometros>17000</quilometros>
		<numportas>5</numportas>
		<lotacao>5</lotacao>
		<imagens><imagem>5.png</imagem></imagens>
		<descricao>Mercedes classe e motorização 300e, styling AMG, câmara de marcha atrás e bancos ventilados e aquecidos. 50 quilómetros de autonomia elétrica!!!</descricao>
	</anuncio>
	<anuncio>
		<id>6</id>
        <venda>naovendido</venda>
		<preco>72000</preco>
		<nome>António</nome>
		<contacto>234234234</contacto>
		<email>pessego@limonada.pt</email>
		<marca>tesla</marca>
		<modelo>s</modelo>
		<cilindrada>0</cilindrada>
		<combustivel>elétrico</combustivel>
		<transmissao>automático</transmissao>
		<registo>2018</registo>
		<mes>maio</mes>
		<estado>usado</estado>
		<potencia>690</potencia>
		<quilometros>27000</quilometros>
		<numportas>5</numportas>
		<lotacao>5</lotacao>
		<imagens><imagem>6.png</imagem></imagens>
		<descricao>Tesla Model S P100D, com premium pack e autopilot.</descricao>
	</anuncio>
	<anuncio>
		<id>7</id>
        <venda>naovendido</venda>
		<preco>10000</preco>
		<nome>Ricardo</nome>
		<contacto>234234277</contacto>
		<email>lima@limonada.pt</email>
		<marca>volkswagen</marca>
		<modelo>polo</modelo>
		<cilindrada>1600</cilindrada>
		<combustivel>gasoleo</combustivel>
		<transmissao>manual</transmissao>
		<registo>2012</registo>
		<mes>novembro</mes>
		<estado>usado</estado>
		<potencia>110</potencia>
		<quilometros>77000</quilometros>
		<numportas>5</numportas>
		<lotacao>5</lotacao>
		<imagens><imagem>7.png</imagem></imagens>
		<descricao>Polo TDI bluemotion, muito económico, com a/c manual.</descricao>
	</anuncio>
	<anuncio>
		<id>8</id>
        <venda>naovendido</venda>
		<preco>34000</preco>
		<nome>Rodrigo</nome>
		<contacto>234234222</contacto>
		<email>laranja@limonada.pt</email>
		<marca>volkswagen</marca>
		<modelo>golf</modelo>
		<cilindrada>1600</cilindrada>
		<combustivel>gasoleo</combustivel>
		<transmissao>manual</transmissao>
		<registo>2020</registo>
		<mes>maio</mes>
		<estado>novo</estado>
		<potencia>130</potencia>
		<quilometros>27</quilometros>
		<numportas>5</numportas>
		<lotacao>5</lotacao>
		<imagens><imagem>8.png</imagem></imagens>
		<descricao>Volkswagen golf TDI com exterior R-Design, cruise control automático, sensores de estacionamento à frente e a atrás.</descricao>
	</anuncio>
	<anuncio>
		<id>9</id>
        <venda>naovendido</venda>
		<preco>159000</preco>
		<nome>Francisco</nome>
		<contacto>234234244</contacto>
		<email>favas@limonada.pt</email>
		<marca>ferrari</marca>
		<modelo>458</modelo>
		<cilindrada>4580</cilindrada>
		<combustivel>gasolina</combustivel>
		<transmissao>automático</transmissao>
		<registo>2012</registo>
		<mes>janeiro</mes>
		<estado>usado</estado>
		<potencia>561</potencia>
		<quilometros>15000</quilometros>
		<numportas>3</numportas>
		<lotacao>2</lotacao>
		<imagens><imagem>9.png</imagem></imagens>
		<descricao>Ferrari 458 spider em rosso rubino, nunca levado à pista já com retrofit oficial da marca para Apple Carplay.</descricao>
	</anuncio>
	<anuncio>
		<id>10</id>
        <venda>naovendido</venda>
		<preco>5000</preco>
		<nome>Pedro</nome>
		<contacto>234234211</contacto>
		<email>tarangina@limonada.pt</email>
		<marca>seat</marca>
		<modelo>ibiza</modelo>
		<cilindrada>2000</cilindrada>
		<combustivel>gasoleo</combustivel>
		<transmissao>manual</transmissao>
		<registo>2005</registo>
		<mes>setembro</mes>
		<estado>usado</estado>
		<potencia>190</potencia>
		<quilometros>107000</quilometros>
		<numportas>5</numportas>
		<lotacao>5</lotacao>
		<imagens><imagem>10.png</imagem></imagens>
		<descricao>Seat ibiza nunca modificado, revisão feita recentemente com a/c manual e cruise control.</descricao>
	</anuncio>
	<anuncio>
		<id>11</id>
        <venda>naovendido</venda>
		<preco>6000</preco>
		<nome>Jorge</nome>
		<contacto>234234999</contacto>
		<email>abacate@limonada.pt</email>
		<marca>alfa romeo</marca>
		<modelo>159</modelo>
		<cilindrada>2200</cilindrada>
		<combustivel>gasoleo</combustivel>
		<transmissao>manual</transmissao>
		<registo>2004</registo>
		<mes>junho</mes>
		<estado>usado</estado>
		<potencia>189</potencia>
		<quilometros>227000</quilometros>
		<numportas>5</numportas>
		<lotacao>5</lotacao>
		<imagens><imagem>11.png</imagem></imagens>
		<descricao>Pintura em bom estado, pneus novos.</descricao>
	</anuncio>
	<anuncio>
		<id>12</id>
        <venda>naovendido</venda>
		<preco>73000</preco>
		<nome>Maria</nome>
		<contacto>234234400</contacto>
		<email>malagueta@limonada.pt</email>
		<marca>bmw</marca>
		<modelo>m2</modelo>
		<cilindrada>2998</cilindrada>
		<combustivel>gasolina</combustivel>
		<transmissao>manual</transmissao>
		<registo>2019</registo>
		<mes>outubro</mes>
		<estado>usado</estado>
		<potencia>410</potencia>
		<quilometros>7600</quilometros>
		<numportas>3</numportas>
		<lotacao>2</lotacao>
		<imagens><imagem>12.png</imagem></imagens>
		<descricao>BMW M2, tem todos extras relacionados com assistências de condução, travões de cerâmica e jantes de magnésio.</descricao>
	</anuncio>
	<anuncio>
		<id>13</id>
        <venda>naovendido</venda>
		<preco>37000</preco>
		<nome>Natália</nome>
		<contacto>234234678</contacto>
		<email>morangos@limonada.pt</email>
		<marca>bmw</marca>
		<modelo>330e</modelo>
		<cilindrada>2000</cilindrada>
		<combustivel>híbrido(gasolina)</combustivel>
		<transmissao>automático</transmissao>
		<registo>2017</registo>
		<mes>fevereiro</mes>
		<estado>usado</estado>
		<potencia>258</potencia>
		<quilometros>37000</quilometros>
		<numportas>5</numportas>
		<lotacao>5</lotacao>
		<imagens><imagem>13.png</imagem></imagens>
		<descricao>Pack M exterior e interior.</descricao>
	</anuncio>
	<anuncio>
		<id>14</id>
        <venda>naovendido</venda>
		<preco>25000</preco>
		<nome>Benecar</nome>
		<contacto>234234234</contacto>
		<email>cerejas@limonada.pt</email>
		<marca>bmw</marca>
		<modelo>118d</modelo>
		<cilindrada>2000</cilindrada>
		<combustivel>gasoleo</combustivel>
		<transmissao>automático</transmissao>
		<registo>2014</registo>
		<mes>julho</mes>
		<estado>usado</estado>
		<potencia>170</potencia>
		<quilometros>27000</quilometros>
		<numportas>5</numportas>
		<lotacao>5</lotacao>
		<imagens><imagem>14.png</imagem></imagens>
		<descricao>Pack exclusive, câmara de marcha atrás cruise control adaptativo e assistência à manutenção da faixa de rodagem.</descricao>
	</anuncio>
	<anuncio>
		<id>15</id>
        <venda>naovendido</venda>
		<preco>31000</preco>
		<nome>Manuel</nome>
		<contacto>234234112</contacto>
		<email>couve@limonada.pt</email>
		<marca>audi</marca>
		<modelo>a7</modelo>
		<cilindrada>2998</cilindrada>
		<combustivel>gasoleo</combustivel>
		<transmissao>automático</transmissao>
		<registo>2011</registo>
		<mes>maio</mes>
